### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by rusnazip** [dle-modules/DLE-vQmod#23]
@webair-studio Планируется ли обновление модуля под версию DLE 12.1? Очень нужный плагин.

**Comment by pafnuty** [comment]
@rusnazip если хотите более быстрой реакции на вопрос, пожалуйста, упоминайте @webair-studio  в комментарии.

**Comment by rusnazip** [comment]
@pafnuty а вы могли бы поправить код для установки под 12.1 ?

**Comment by pafnuty** [comment]
Думаю лучше всего получится это сделать у автора.

15 февр. 2018 г. 1:05 ПП пользователь "rusnazip" <notifications@github.com>
написал:
